id: P006981
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:34:12.341220
source_metadata:
  id: bdr:W3CN6943
  title: འབྲས་སྤུངས་ཀྱི་གདན་རབས་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    eed13c38e4c440a791e2571d6061f230:
      image_group_id: I3CN6945
      title: Volume 1 of dpal ldan 'bras dkar spungs pa'i gdan rabs rim byon gyi rnam
        thar/
      volume_number: 1
      total_pages: 284
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
