id: P006981
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6943
  title: འབྲས་སྤུངས་ཀྱི་གདན་རབས་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    bf3347f943bb4aefb69bbbefaffe2052:
      image_group_id: I3CN6945
      title: ''
      volume_number: 1
      total_pages: 284
ebook_metadata:
  title: འབྲས་སྤུངས་ཀྱི་གདན་རབས་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  sku: P006981
  cover: cover.jpg
  layers:
  - pagination
