id: IFF30FFFE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:44:15+00:00'
last_modified: '2022-06-08T09:46:31.763245+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6943
  title: འབྲས་སྤུངས་ཀྱི་གདན་རབས་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8C2F:
      image_group_id: I3CN6945
      title: Volume 1 of dpal ldan 'bras dkar spungs pa'i gdan rabs rim byon gyi rnam
        thar/
      total_pages: 284
      order: 1
      base_file: 8C2F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
